language: node_js
node_js:
  - "node"

services:
  - postgresql

postgres:
  adapter: postgresql
  database: test_todo_dev
  username: postgres

before_script:
  - psql -c 'create database test_todo_dev;' -U postgres
  - npm install sequelize-cli -g
  - chmod 0777 ./node_modules/.bin/mocha

script: 
  - npm run test:server
