/**
* Action types for the reducer
*/

/* Authentication */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const LOGOUT = 'LOGOUT';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

/* Todo */
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
export const GET_TODO_FAILED = 'GET_TODO_FAILED';
export const GET_SINGLE_TODO_SUCCESS = 'GET_SINGLE_TODO_SUCCESS';
export const GET_SINGLE_TODO_FAILED = 'GET_SINGLE_TODO_FAILED';
export const SAVE_TODO_SUCCESS = 'SAVE_TODO_SUCCESS';
export const SAVE_TODO_FAILED = 'SAVE_TODO_FAILED';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILED = 'DELETE_TODO_FAILED';

/* Todo Items */
export const GET_TODOITEMS_SUCCESS = 'GET_TODOITEMS_SUCCESS';
export const GET_TODOITEMS_FAILED = 'GET_TODOITEMS_FAILED';
export const SAVE_TODOITEMS_SUCCESS = 'SAVE_TODOITEMS_SUCCESS';
export const SAVE_TODOITEMS_FAILED = 'SAVE_TODOITEMS_FAILED';
export const DELETE_TODOITEMS_SUCCESS = 'DELETE_TODOITEMS_SUCCESS';
export const DELETE_TODOITEMS_FAILED = 'DELETE_TODOITEMS_FAILED';

/* Ajax calls */
export const BEGIN_LOADING = 'BEGIN_LOADING';
export const END_LOADING= 'END_LOADING';
